# Generated by Django 5.0.3 on 2026-03-30 03:42

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='login_id',
            field=models.UUIDField(default=uuid.UUID('e59bd6eb-e15b-46a6-8409-af54ae210af8'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
