# Generated by Django 5.0.3 on 2026-03-30 03:48

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_login_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='login_id',
            field=models.UUIDField(default=uuid.UUID('82afc6d7-320b-4eeb-adba-680dc388727d'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
