# Generated by Django 5.0.3 on 2026-03-28 16:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackedCase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnr_number', models.CharField(db_index=True, max_length=16)),
                ('court_state', models.CharField(max_length=100)),
                ('court_district', models.CharField(max_length=100)),
                ('case_type', models.CharField(max_length=100)),
                ('case_number', models.CharField(max_length=50)),
                ('year', models.IntegerField()),
                ('petitioner', models.CharField(max_length=255)),
                ('respondent', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('last_checked', models.DateTimeField(auto_now_add=True)),
                ('last_changed', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_changed'],
                'unique_together': {('user', 'cnr_number')},
            },
        ),
        migrations.CreateModel(
            name='CaseHearing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hearing_date', models.DateField()),
                ('purpose', models.CharField(max_length=255)),
                ('next_hearing_date', models.DateField(blank=True, null=True)),
                ('judge_name', models.CharField(blank=True, max_length=255, null=True)),
                ('raw_data', models.JSONField(default=dict)),
                ('tracked_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hearings', to='cases.trackedcase')),
            ],
            options={
                'ordering': ['-hearing_date'],
            },
        ),
    ]
