# Generated by Django 5.0.3 on 2026-03-30 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CaseHearing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hearing_date', models.DateField()),
                ('purpose', models.CharField(max_length=255)),
                ('next_hearing_date', models.DateField(blank=True, null=True)),
                ('judge_name', models.CharField(blank=True, max_length=255, null=True)),
                ('raw_data', models.JSONField(default=dict)),
            ],
            options={
                'ordering': ['-hearing_date'],
            },
        ),
        migrations.CreateModel(
            name='TrackedCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnr_number', models.CharField(db_index=True, max_length=16)),
                ('court_state', models.CharField(max_length=100)),
                ('court_district', models.CharField(max_length=100)),
                ('case_type', models.CharField(max_length=100)),
                ('case_number', models.CharField(max_length=50)),
                ('year', models.IntegerField()),
                ('petitioner', models.CharField(max_length=255)),
                ('respondent', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('last_checked', models.DateTimeField(auto_now_add=True)),
                ('last_changed', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-last_changed'],
            },
        ),
    ]
