# Generated by Django 5.0.3 on 2026-03-30 03:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cases', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='trackedcase',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cases', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='casehearing',
            name='tracked_case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hearings', to='cases.trackedcase'),
        ),
        migrations.AlterUniqueTogether(
            name='trackedcase',
            unique_together={('user', 'cnr_number')},
        ),
    ]
